/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSetOrganisationRouteImport } from './routes/_auth/set-organisation'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthCreateOrganisationRouteImport } from './routes/_auth/create-organisation'
import { Route as AuthAcceptInvitationInvitationIdRouteImport } from './routes/_auth/accept-invitation.$invitationId'

const ProtectedOrgOrgIdIndexLazyRouteImport = createFileRoute(
  '/_protected/org/$orgId/',
)()
const ProtectedOrgOrgIdUserUserIdLazyRouteImport = createFileRoute(
  '/_protected/org/$orgId/user/$userId',
)()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/_auth/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetOrganisationRoute = AuthSetOrganisationRouteImport.update({
  id: '/_auth/set-organisation',
  path: '/set-organisation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/_auth/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/_auth/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCreateOrganisationRoute = AuthCreateOrganisationRouteImport.update({
  id: '/_auth/create-organisation',
  path: '/create-organisation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAcceptInvitationInvitationIdRoute =
  AuthAcceptInvitationInvitationIdRouteImport.update({
    id: '/_auth/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedOrgOrgIdIndexLazyRoute =
  ProtectedOrgOrgIdIndexLazyRouteImport.update({
    id: '/_protected/org/$orgId/',
    path: '/org/$orgId/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/_protected/org/$orgId/index.lazy').then((d) => d.Route),
  )
const ProtectedOrgOrgIdUserUserIdLazyRoute =
  ProtectedOrgOrgIdUserUserIdLazyRouteImport.update({
    id: '/_protected/org/$orgId/user/$userId',
    path: '/org/$orgId/user/$userId',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/_protected/org/$orgId/user/$userId.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-organisation': typeof AuthCreateOrganisationRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/set-organisation': typeof AuthSetOrganisationRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/org/$orgId': typeof ProtectedOrgOrgIdIndexLazyRoute
  '/org/$orgId/user/$userId': typeof ProtectedOrgOrgIdUserUserIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-organisation': typeof AuthCreateOrganisationRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/set-organisation': typeof AuthSetOrganisationRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/org/$orgId': typeof ProtectedOrgOrgIdIndexLazyRoute
  '/org/$orgId/user/$userId': typeof ProtectedOrgOrgIdUserUserIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth/create-organisation': typeof AuthCreateOrganisationRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/set-organisation': typeof AuthSetOrganisationRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/_protected/org/$orgId/': typeof ProtectedOrgOrgIdIndexLazyRoute
  '/_protected/org/$orgId/user/$userId': typeof ProtectedOrgOrgIdUserUserIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-organisation'
    | '/forgot-password'
    | '/reset-password'
    | '/set-organisation'
    | '/sign-in'
    | '/sign-up'
    | '/accept-invitation/$invitationId'
    | '/org/$orgId'
    | '/org/$orgId/user/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-organisation'
    | '/forgot-password'
    | '/reset-password'
    | '/set-organisation'
    | '/sign-in'
    | '/sign-up'
    | '/accept-invitation/$invitationId'
    | '/org/$orgId'
    | '/org/$orgId/user/$userId'
  id:
    | '__root__'
    | '/'
    | '/_auth/create-organisation'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/set-organisation'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/accept-invitation/$invitationId'
    | '/_protected/org/$orgId/'
    | '/_protected/org/$orgId/user/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCreateOrganisationRoute: typeof AuthCreateOrganisationRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSetOrganisationRoute: typeof AuthSetOrganisationRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthAcceptInvitationInvitationIdRoute: typeof AuthAcceptInvitationInvitationIdRoute
  ProtectedOrgOrgIdIndexLazyRoute: typeof ProtectedOrgOrgIdIndexLazyRoute
  ProtectedOrgOrgIdUserUserIdLazyRoute: typeof ProtectedOrgOrgIdUserUserIdLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/set-organisation': {
      id: '/_auth/set-organisation'
      path: '/set-organisation'
      fullPath: '/set-organisation'
      preLoaderRoute: typeof AuthSetOrganisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/create-organisation': {
      id: '/_auth/create-organisation'
      path: '/create-organisation'
      fullPath: '/create-organisation'
      preLoaderRoute: typeof AuthCreateOrganisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/accept-invitation/$invitationId': {
      id: '/_auth/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AuthAcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/org/$orgId/': {
      id: '/_protected/org/$orgId/'
      path: '/org/$orgId'
      fullPath: '/org/$orgId'
      preLoaderRoute: typeof ProtectedOrgOrgIdIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/org/$orgId/user/$userId': {
      id: '/_protected/org/$orgId/user/$userId'
      path: '/org/$orgId/user/$userId'
      fullPath: '/org/$orgId/user/$userId'
      preLoaderRoute: typeof ProtectedOrgOrgIdUserUserIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCreateOrganisationRoute: AuthCreateOrganisationRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSetOrganisationRoute: AuthSetOrganisationRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthAcceptInvitationInvitationIdRoute: AuthAcceptInvitationInvitationIdRoute,
  ProtectedOrgOrgIdIndexLazyRoute: ProtectedOrgOrgIdIndexLazyRoute,
  ProtectedOrgOrgIdUserUserIdLazyRoute: ProtectedOrgOrgIdUserUserIdLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
