name = "yapyup-marketing"
compatibility_date = "2025-06-12"
routes = [
    { pattern = "yapyup.com/*", zone_name = "yapyup.com" },
    { pattern = "www.yapyup.com/*", zone_name = "yapyup.com" }
]

[assets]
directory = "./dist/"
not_found_handling = "404-page"